import localFont from "next/font/local";
import "./globals.css";

// Pretendard 폰트 설정
const pretendard = localFont({
  src: [
    {
      path: "./fonts/PretendardVariable.woff2",
      weight: "100 900", // Pretendard Variable은 모든 굵기를 포함
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-pretendard", // CSS 변수로 폰트 설정
});

export const metadata = {
  title: "한국리서치 패널모집 광고관리자",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={`${pretendard.variable} bg-gray-100`}>
      <body>{children}</body>
    </html>
  );
}
